### PR TITLE
Update JsonImporter.php

### PR DESCRIPTION
**Pull request by gassenta**

### CODE REVIEW

**Comment by mathieutu** [comment]
@gabry2899 Could you please explain why you need this modification?
And could you add some tests that use your update?

**Comment by gassenta** [comment]
It is just a quick patch... I needed to make it work yesterday. I don't know why but a null variable was being sent as first argument for wrap and it was causing an error.

**Comment by gassenta** [comment]
`Argument 1 passed to MathieuTu\JsonSyncer\Helpers\JsonImporter::wrap() must be of the type array, null given, called in /var/app/current/vendor/mathieutu/laravel-json-syncer/src/Helpers/JsonImporter.php on line 69`

**Comment by mathieutu** [comment]
Ok, thanks. Could you give me the value you passed initially to the Importer, to understand why the parameter passed to `wrap` method is null?

I think I've understood and I'm currently publishing a fix, but I just want to be sure that this is the actual problem.

**Comment by mathieutu** [comment]
It should be fixed now with `1.1.0` version. 
Please feel free to reopen an issue if not.

**Pull request closed without merging**
