### PR TITLE
📦 Implement Laravel 7 compatibility

### PR DESCRIPTION
**Pull request by rdarcy1**

### CODE REVIEW

**Comment by mathieutu** [comment]
Hi, Thanks for the PR!

Could you please update the travis.yml too to include the 7.0 version ?

Thanks.

**Comment by rdarcy1** [comment]
I've given it a go, hopefully it's right 😄

**Comment by mathieutu** [comment]
It seems to be! 
Thanks, I'll tag it soon.

**Comment by mathieutu** [comment]
Here we go ! 
https://github.com/mathieutu/laravel-json-syncer/releases/tag/1.3.0

**Pull request merged**
